Shrkanch external pt
awsluja/amplify-cli pull request #3
Opened 2023-04-26 18:35 UTC by shrkanchExternal

#### Description of changes

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] [Pull request labels](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#labels) are added

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-26 19:13 UTC, awsluja commented on .circleci/publish-codebuild.sh
> +#!/bin/bash -e
commenting here for test

2023-04-26 19:14 UTC, awsluja requested changes
requesting some changes. - test

2023-04-26 19:14 UTC, shrkanchExternal commented on .circleci/publish-codebuild.sh
> +#!/bin/bash -e
Thanks.

2023-04-26 19:45 UTC, shrkanchExternal commented
Hi,

2023-04-27 17:42 UTC, shrkanchExternal reviewed
this is test.

2023-04-27 21:05 UTC, shrkanchExternal reviewed
this is for testing purpose only.

2023-04-27 21:07 UTC, shrkanchExternal commented
`"'><img src='onerror=javascript:alert(1)>

2023-04-28 14:43 UTC, closed without merging